title: Abdelaziz BOUZIANI # your name (or website title) here
logo: "/images/Photo1_2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science portfolio
  <br><br>
  Contact me
  <br><br>
  <a href="https://www.linkedin.com/in/abdelaziz-bouziani/">Linkedin Account</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
